[package]
name = "terminal"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
alacritty_terminal = "0.26"
gpui = { git = "https://github.com/zed-industries/zed" }
gpui-component = { git = "https://github.com/longbridge/gpui-component", branch = "main" }
ui = { path = "../ui" }
flume = "0.11"
polling = "3"
parking_lot = "0.12"
anyhow = "1"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
gpui = { git = "https://github.com/zed-industries/zed", features = ["test-support"] }
